### ISSUE TITLE
Exception thrown on number somewhere inside TimeNormFinder

### ISSUE THREAD

**Issue by kwalcock** [clulab/timenorm#51]
FWIW I'm working on branch DART4-42k, running ExtractDartMetaFromDirectory.  Another ExtractFromDirectory, maybe even from master, should hopefully work as well since I'm not yet attaching the Dart Metadata.

Here's the text file: [7b0c4e54e7764390c9824bf66776f898.txt](https://github.com/clulab/timenorm/files/3935753/7b0c4e54e7764390c9824bf66776f898.txt)

Here's the exception:

```
..\elasticsearchDart\2019Thanksgiving2\badtext\7b0c4e54e7764390c9824bf66776f898.txt

java.lang.NumberFormatException: For input string: "20110805000336031965"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_181]
	at java.lang.Integer.parseInt(Integer.java:583) ~[na:1.8.0_181]
	at java.lang.Integer.parseInt(Integer.java:615) ~[na:1.8.0_181]
	at scala.collection.immutable.StringLike.toInt(StringLike.scala:301) ~[scala-library-2.12.4.jar:na]
	at scala.collection.immutable.StringLike.toInt$(StringLike.scala:301) ~[scala-library-2.12.4.jar:na]
	at scala.collection.immutable.StringOps.toInt(StringOps.scala:29) ~[scala-library-2.12.4.jar:na]
	at org.clulab.timenorm.scfg.SynchronousParser.$anonfun$parseChart$2(SynchronousParser.scala:78) ~[timenorm_2.12-1.0.2.jar:1.0.2]
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:156) ~[scala-library-2.12.4.jar:na]
	at org.clulab.timenorm.scfg.SynchronousParser.parseChart(SynchronousParser.scala:75) ~[timenorm_2.12-1.0.2.jar:1.0.2]
	at org.clulab.timenorm.scfg.SynchronousParser.parseAll(SynchronousParser.scala:38) ~[timenorm_2.12-1.0.2.jar:1.0.2]
	at org.clulab.timenorm.scfg.SynchronousParser.$anonfun$tryParseAll$1(SynchronousParser.scala:65) ~[timenorm_2.12-1.0.2.jar:1.0.2]
	at scala.util.control.Exception$Catch.$anonfun$withTry$1(Exception.scala:253) ~[scala-library-2.12.4.jar:na]
	at scala.util.control.Exception$Catch.apply(Exception.scala:224) ~[scala-library-2.12.4.jar:na]
	at scala.util.control.Exception$Catch.withTry(Exception.scala:253) ~[scala-library-2.12.4.jar:na]
	at org.clulab.timenorm.scfg.SynchronousParser.tryParseAll(SynchronousParser.scala:65) ~[timenorm_2.12-1.0.2.jar:1.0.2]
	at org.clulab.timenorm.scate.WordsToNumber.apply(WordsToNumber.scala:25) ~[timenorm_2.12-1.0.2.jar:1.0.2]
	at org.clulab.timenorm.scate.TemporalNeuralParser.$anonfun$inferProperties$1(TemporalNeuralParser.scala:307) ~[timenorm_2.12-1.0.2.jar:1.0.2]
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234) ~[scala-library-2.12.4.jar:na]
	at scala.collection.Iterator.foreach(Iterator.scala:929) ~[scala-library-2.12.4.jar:na]
	at scala.collection.Iterator.foreach$(Iterator.scala:929) ~[scala-library-2.12.4.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417) ~[scala-library-2.12.4.jar:na]
	at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:178) ~[scala-library-2.12.4.jar:na]
	at scala.collection.TraversableLike.map(TraversableLike.scala:234) ~[scala-library-2.12.4.jar:na]
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227) ~[scala-library-2.12.4.jar:na]
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47) ~[scala-library-2.12.4.jar:na]
	at scala.collection.SetLike.map(SetLike.scala:101) ~[scala-library-2.12.4.jar:na]
	at scala.collection.SetLike.map$(SetLike.scala:101) ~[scala-library-2.12.4.jar:na]
	at scala.collection.AbstractSet.map(Set.scala:47) ~[scala-library-2.12.4.jar:na]
	at org.clulab.timenorm.scate.TemporalNeuralParser.inferProperties(TemporalNeuralParser.scala:293) ~[timenorm_2.12-1.0.2.jar:1.0.2]
	at org.clulab.timenorm.scate.TemporalNeuralParser.$anonfun$parseBatchToXML$5(TemporalNeuralParser.scala:170) ~[timenorm_2.12-1.0.2.jar:1.0.2]
	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:739) ~[scala-library-2.12.4.jar:na]
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32) ~[scala-library-2.12.4.jar:na]
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29) ~[scala-library-2.12.4.jar:na]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191) ~[scala-library-2.12.4.jar:na]
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:738) ~[scala-library-2.12.4.jar:na]
	at org.clulab.timenorm.scate.TemporalNeuralParser.$anonfun$parseBatchToXML$3(TemporalNeuralParser.scala:164) ~[timenorm_2.12-1.0.2.jar:1.0.2]
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234) ~[scala-library-2.12.4.jar:na]
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32) ~[scala-library-2.12.4.jar:na]
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29) ~[scala-library-2.12.4.jar:na]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191) ~[scala-library-2.12.4.jar:na]
	at scala.collection.TraversableLike.map(TraversableLike.scala:234) ~[scala-library-2.12.4.jar:na]
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227) ~[scala-library-2.12.4.jar:na]
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:191) ~[scala-library-2.12.4.jar:na]
	at org.clulab.timenorm.scate.TemporalNeuralParser.parseBatchToXML(TemporalNeuralParser.scala:163) ~[timenorm_2.12-1.0.2.jar:1.0.2]
	at org.clulab.wm.eidos.context.TimeNormFinder.parseBatch(TimeNormFinder.scala:91) ~[classes/:na]
	at org.clulab.wm.eidos.context.TimeNormFinder.$anonfun$find$13(TimeNormFinder.scala:171) ~[classes/:na]
	at org.clulab.wm.eidos.context.TimeNormFinder.$anonfun$find$13$adapted(TimeNormFinder.scala:171) ~[classes/:na]
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:473) ~[scala-library-2.12.4.jar:na]
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:479) ~[scala-library-2.12.4.jar:na]
	at scala.collection.Iterator.foreach(Iterator.scala:929) ~[scala-library-2.12.4.jar:na]
	at scala.collection.Iterator.foreach$(Iterator.scala:929) ~[scala-library-2.12.4.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417) ~[scala-library-2.12.4.jar:na]
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:59) ~[scala-library-2.12.4.jar:na]
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:50) ~[scala-library-2.12.4.jar:na]
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104) ~[scala-library-2.12.4.jar:na]
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48) ~[scala-library-2.12.4.jar:na]
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:310) ~[scala-library-2.12.4.jar:na]
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:308) ~[scala-library-2.12.4.jar:na]
	at scala.collection.AbstractIterator.to(Iterator.scala:1417) ~[scala-library-2.12.4.jar:na]
	at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:302) ~[scala-library-2.12.4.jar:na]
	at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:302) ~[scala-library-2.12.4.jar:na]
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1417) ~[scala-library-2.12.4.jar:na]
	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:289) ~[scala-library-2.12.4.jar:na]
	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:283) ~[scala-library-2.12.4.jar:na]
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1417) ~[scala-library-2.12.4.jar:na]
	at org.clulab.wm.eidos.context.TimeNormFinder.find(TimeNormFinder.scala:172) ~[classes/:na]
	at org.clulab.wm.eidos.EidosSystem.$anonfun$extractFrom$1(EidosSystem.scala:65) ~[classes/:na]
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122) ~[scala-library-2.12.4.jar:na]
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118) ~[scala-library-2.12.4.jar:na]
	at scala.collection.immutable.List.foldLeft(List.scala:86) ~[scala-library-2.12.4.jar:na]
	at org.clulab.wm.eidos.EidosSystem.extractFrom(EidosSystem.scala:64) ~[classes/:na]
	at org.clulab.wm.eidos.EidosSystem.extractFromDoc(EidosSystem.scala:92) ~[classes/:na]
	at org.clulab.wm.eidos.EidosSystem.extractFromTextWithDct(EidosSystem.scala:150) ~[classes/:na]
	at org.clulab.wm.eidos.apps.batch.ExtractDartMetaFromDirectory$.$anonfun$new$3(ExtractDartMetaFromDirectory.scala:75) [classes/:na]
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:12) ~[scala-library-2.12.4.jar:na]
	at org.clulab.wm.eidos.utils.Timer.time(Timer.scala:11) ~[classes/:na]
	at org.clulab.wm.eidos.apps.batch.ExtractDartMetaFromDirectory$.$anonfun$new$2(ExtractDartMetaFromDirectory.scala:66) [classes/:na]
	at org.clulab.wm.eidos.apps.batch.ExtractDartMetaFromDirectory$.$anonfun$new$2$adapted(ExtractDartMetaFromDirectory.scala:61) [classes/:na]
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32) ~[scala-library-2.12.4.jar:na]
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29) ~[scala-library-2.12.4.jar:na]
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38) ~[scala-library-2.12.4.jar:na]
	at org.clulab.wm.eidos.apps.batch.ExtractDartMetaFromDirectory$.$anonfun$new$1(ExtractDartMetaFromDirectory.scala:61) [classes/:na]
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12) ~[scala-library-2.12.4.jar:na]
	at org.clulab.wm.eidos.utils.Timer$.time(Timer.scala:41) ~[classes/:na]
	at org.clulab.wm.eidos.apps.batch.ExtractDartMetaFromDirectory$.delayedEndpoint$org$clulab$wm$eidos$apps$batch$ExtractDartMetaFromDirectory$1(ExtractDartMetaFromDirectory.scala:39) [classes/:na]
	at org.clulab.wm.eidos.apps.batch.ExtractDartMetaFromDirectory$delayedInit$body.apply(ExtractDartMetaFromDirectory.scala:24) ~[classes/:na]
	at scala.Function0.apply$mcV$sp(Function0.scala:34) ~[scala-library-2.12.4.jar:na]
	at scala.Function0.apply$mcV$sp$(Function0.scala:34) ~[scala-library-2.12.4.jar:na]
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12) ~[scala-library-2.12.4.jar:na]
	at scala.App.$anonfun$main$1$adapted(App.scala:76) ~[scala-library-2.12.4.jar:na]
	at scala.collection.immutable.List.foreach(List.scala:389) ~[scala-library-2.12.4.jar:na]
	at scala.App.main(App.scala:76) ~[scala-library-2.12.4.jar:na]
	at scala.App.main$(App.scala:74) ~[scala-library-2.12.4.jar:na]
	at org.clulab.wm.eidos.apps.batch.ExtractDartMetaFromDirectory$.main(ExtractDartMetaFromDirectory.scala:24) [classes/:na]
	at org.clulab.wm.eidos.apps.batch.ExtractDartMetaFromDirectory.main(ExtractDartMetaFromDirectory.scala) ~[classes/:na]
```

**Comment by EgoLaparra** [comment]
The number is simply to large to be converted to Int. 

@bethard, maybe we could change https://github.com/clulab/timenorm/blob/e638b915405bf5968036e937d381cff94ba4be84/src/main/scala/org/clulab/timenorm/scfg/SynchronousGrammar.scala#L117 to check if the string is a valid integer.

**Comment by kwalcock** [comment]
I don't suppose there's an `Integer.parseInt(myString)` somewhere nearby that can be put into an exception handler?

**Comment by kwalcock** [comment]
Here, mayble: https://github.com/clulab/timenorm/blob/e638b915405bf5968036e937d381cff94ba4be84/src/main/scala/org/clulab/timenorm/scfg/SynchronousParser.scala#L78?
