### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by kwalcock** [clulab/timenorm#53]
I'm seeing this exception for the file [618071f4e11c1c7eb3ef0ae20bd001c2.txt](https://github.com/clulab/timenorm/files/3961673/618071f4e11c1c7eb3ef0ae20bd001c2.txt)

```
03:48:32.315 [ForkJoinPool-4-worker-39] ERROR o.c.w.e.a.b.ExtractDartMetaFromDirectory$ - Exception for file ../corpora/2019Thanksgiving4/text/clara/618071f4e11c1c7eb3ef0ae20bd001c2.txt
java.lang.StringIndexOutOfBoundsException: String index out of range: 92020
	at java.lang.String.substring(String.java:1963) ~[na:1.8.0_131]
	at org.clulab.timenorm.scate.TemporalNeuralParser.$anonfun$parseBatchToXML$5(TemporalNeuralParser.scala:167) ~[timenorm_2.12-1.0.2.jar:1.0.2]
	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:739) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:738) ~[scala-library-2.12.4.jar:1.0.4]
	at org.clulab.timenorm.scate.TemporalNeuralParser.$anonfun$parseBatchToXML$3(TemporalNeuralParser.scala:164) ~[timenorm_2.12-1.0.2.jar:1.0.2]
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.TraversableLike.map(TraversableLike.scala:234) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:191) ~[scala-library-2.12.4.jar:1.0.4]
	at org.clulab.timenorm.scate.TemporalNeuralParser.parseBatchToXML(TemporalNeuralParser.scala:163) ~[timenorm_2.12-1.0.2.jar:1.0.2]
	at org.clulab.wm.eidos.context.TimeNormFinder.parseBatch(TimeNormFinder.scala:91) ~[eidos_2.12-0.2.3-SNAPSHOT.jar:0.2.3-SNAPSHOT]
	at org.clulab.wm.eidos.context.TimeNormFinder.$anonfun$find$13(TimeNormFinder.scala:171) ~[eidos_2.12-0.2.3-SNAPSHOT.jar:0.2.3-SNAPSHOT]
	at org.clulab.wm.eidos.context.TimeNormFinder.$anonfun$find$13$adapted(TimeNormFinder.scala:171) ~[eidos_2.12-0.2.3-SNAPSHOT.jar:0.2.3-SNAPSHOT]
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:473) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:479) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.Iterator.foreach(Iterator.scala:929) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.Iterator.foreach$(Iterator.scala:929) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:59) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:50) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:310) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:308) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.AbstractIterator.to(Iterator.scala:1417) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:302) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:302) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1417) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:289) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:283) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1417) ~[scala-library-2.12.4.jar:1.0.4]
	at org.clulab.wm.eidos.context.TimeNormFinder.find(TimeNormFinder.scala:172) ~[eidos_2.12-0.2.3-SNAPSHOT.jar:0.2.3-SNAPSHOT]
	at org.clulab.wm.eidos.EidosSystem.$anonfun$extractFrom$1(EidosSystem.scala:65) ~[eidos_2.12-0.2.3-SNAPSHOT.jar:0.2.3-SNAPSHOT]
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.immutable.List.foldLeft(List.scala:86) ~[scala-library-2.12.4.jar:1.0.4]
	at org.clulab.wm.eidos.EidosSystem.extractFrom(EidosSystem.scala:64) ~[eidos_2.12-0.2.3-SNAPSHOT.jar:0.2.3-SNAPSHOT]
	at org.clulab.wm.eidos.EidosSystem.extractFromDoc(EidosSystem.scala:92) ~[eidos_2.12-0.2.3-SNAPSHOT.jar:0.2.3-SNAPSHOT]
	at org.clulab.wm.eidos.EidosSystem.extractFromTextWithDct(EidosSystem.scala:150) ~[eidos_2.12-0.2.3-SNAPSHOT.jar:0.2.3-SNAPSHOT]
	at org.clulab.wm.eidos.apps.batch.ExtractDartMetaFromDirectory$.$anonfun$new$3(ExtractDartMetaFromDirectory.scala:75) [eidos_2.12-0.2.3-SNAPSHOT.jar:0.2.3-SNAPSHOT]
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:12) ~[scala-library-2.12.4.jar:na]
	at org.clulab.wm.eidos.utils.Timer.time(Timer.scala:11) ~[eidos_2.12-0.2.3-SNAPSHOT.jar:0.2.3-SNAPSHOT]
	at org.clulab.wm.eidos.apps.batch.ExtractDartMetaFromDirectory$.$anonfun$new$2(ExtractDartMetaFromDirectory.scala:66) [eidos_2.12-0.2.3-SNAPSHOT.jar:0.2.3-SNAPSHOT]
	at org.clulab.wm.eidos.apps.batch.ExtractDartMetaFromDirectory$.$anonfun$new$2$adapted(ExtractDartMetaFromDirectory.scala:61) [eidos_2.12-0.2.3-SNAPSHOT.jar:0.2.3-SNAPSHOT]
	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:142) ~[scala-library-2.12.4.jar:na]
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:970) ~[scala-library-2.12.4.jar:na]
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49) ~[scala-library-2.12.4.jar:na]
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12) ~[scala-library-2.12.4.jar:na]
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63) ~[scala-library-2.12.4.jar:1.0.4]
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52) ~[scala-library-2.12.4.jar:na]
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46) ~[scala-library-2.12.4.jar:na]
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:967) ~[scala-library-2.12.4.jar:na]
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:166) ~[scala-library-2.12.4.jar:na]
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:153) ~[scala-library-2.12.4.jar:na]
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440) ~[scala-library-2.12.4.jar:na]
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:146) ~[scala-library-2.12.4.jar:na]
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145) ~[scala-library-2.12.4.jar:na]
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440) ~[scala-library-2.12.4.jar:na]
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189) ~[na:1.8.0_131]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_131]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_131]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_131]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_131]
```

**Comment by kwalcock** [comment]
Also for this file: [841c0a7e9806e4d298804311b360573e.txt](https://github.com/clulab/timenorm/files/3961683/841c0a7e9806e4d298804311b360573e.txt)

**Comment by EgoLaparra** [comment]
This is caused by characters like `𝜃`. In java, this is encoded as 2 characters: `\ud835\udf03`, but, for some weird reason, the following line:

https://github.com/clulab/timenorm/blob/bcdbbc4d62149205b0b3d21a3cfba7a83ae98bda/src/main/scala/org/clulab/timenorm/scate/TemporalNeuralParser.scala#L166

treats it a single character. Thus, the original and resulting strings have different lengths. I'm trying to solve it.

**Comment by kwalcock** [comment]
It seems to require 4-bytes to represent it in UTF-8.  Is it a unicode-32 character?

**Comment by EgoLaparra** [comment]
Yes, it is. https://www.fileformat.info/info/unicode/char/1d703/index.htm
Any suggestion about how to deal with this kind of characters?

**Comment by kwalcock** [comment]
FWIW there are 8 files that exhibit the problem.  I can supply more.

**Comment by kwalcock** [comment]
> Yes, it is. https://www.fileformat.info/info/unicode/char/1d703/index.htm
> Any suggestion about how to deal with this kind of characters?

Not yet, but I'll try to change that.  For the time being I'd be happy to have an update on the large number and double control character files.  I could rerun them then.

**Comment by EgoLaparra** [comment]
Ok, I'm releasing a new version of the time-parser to sonatype.

**Comment by EgoLaparra** [comment]
A possible solution could be normalizing the text: https://docs.oracle.com/javase/tutorial/i18n/text/normalizerapi.html
Something like `Normalizer.normalize("𝜃", Normalizer.Form.NFKC)` returns a string of length 1.

**Comment by bethard** [comment]
Maybe something like:
```
"""[^\u0009\u000A\u000D\u0020-\uD7FF\uE000-\uFFFD]""".r.replaceAllIn(s, " " * _.group(0).length)
```
Where you create `n` spaces, depending on how long the match is?

**Comment by kwalcock** [comment]
If this is the only problematic regular expression, then I'd try doing the replacement manually.  Here's an example that seems to work:
```scala
package com.keithalcock.unicode32

object Unicode32 extends App {

  // The interval is [lo, hi).
  case class CharRange(lo: Int, hi: Int) {

    def contains(value: Int): Boolean = lo <= value && value < hi
  }

  object CharRange {

    def apply(lo: Int, hi: Int, inclusive: Boolean = false): CharRange =
        if (inclusive) new CharRange(lo, hi + 1)
        else new CharRange(lo, hi)

    def apply(hilo: Int): CharRange = apply(hilo, hilo, true)
  }

  abstract class Filter(charRanges: Seq[CharRange]) {

    def contains(letter: Char): Boolean = charRanges.exists(_.contains(letter))

    def filter(text: String, replacement: Char): String
  }

  class Includer(charRanges: Seq[CharRange]) extends Filter(charRanges) {

    def filter(text: String, replacement: Char): String = {
      text.map { letter =>
        if (contains(letter)) letter
        else replacement
      }
    }

  }

  class Excluder(charRanges: Seq[CharRange]) extends Filter(charRanges) {

    def filter(text: String, replacement: Char): String = {
      text.map { letter =>
        if (contains(letter)) replacement
        else letter
      }
    }
  }

  val includer = new Includer(Seq(
    CharRange(0x0009),
    CharRange(0x000A),
    CharRange(0x000D),
    CharRange(0x0020, 0xd7ff, inclusive = true),
    CharRange(0xe000, 0xfffd, inclusive = true)
  ))

  println(includer.filter("a\u0009b\u000ac\u000dd\u0020e\ud7fff\ue000g\ufffdh", '-'))
  println(includer.filter("a\u0008b\u000bc\u000ed\u001fe\ud800f\udfffg\ufffeh", '-'))
  println(includer.filter("a\u0008b\u000bc\u000ed\u001fe\ud800f\udfffg\ufffeh", '-'))
  println(includer.filter("a\ud835\udf03b\ud835c\udf03d\ud835e\udf03\ud835f", '-'))
}
```

**Comment by bethard** [comment]
What's the benefit of all those lines of code over my one-liner?

**Comment by EgoLaparra** [comment]
This is solved in https://github.com/clulab/timenorm/pull/57
